apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cache.slys.dev/v1alpha1",
          "kind": "NodeExporter",
          "metadata": {
            "labels": {
              "app.kubernetes.io/name": "monitoring-stack",
              "app.kubernetes.io/part-of": "node-exporter-operator"
            },
            "name": "monitoring-stack",
            "namespace": "monitoring"
          },
          "spec": {
            "blackboxExporterSettings": {
              "enabled": true
            },
            "kubeStateMetricsSettings": {
              "enabled": true
            },
            "nodeExporterSettings": {
              "enabled": true
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-03-28T13:21:08Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: node-exporter-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeExporter is the Schema for the nodeexporters API
      displayName: Node Exporter
      kind: NodeExporter
      name: nodeexporters.cache.slys.dev
      specDescriptors:
      - displayName: Blackbox Exporter Settings
        path: blackboxExporter
      - displayName: Enabled
        path: blackboxExporter.enabled
      - displayName: Kube State Metrics Settings
        path: kubeStateMetrics
      - displayName: Enabled
        path: kubeStateMetrics.enabled
      - displayName: Node Exporter Settings
        path: nodeExporter
      - displayName: Enabled
        path: nodeExporter.enabled
      version: v1alpha1
  description: node-exporter-operator
  displayName: node-exporter-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - exporter.slys.dev
          resources:
          - nodeexporters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - exporter.slys.dev
          resources:
          - nodeexporters/finalizers
          verbs:
          - update
        - apiGroups:
          - exporter.slys.dev
          resources:
          - nodeexporters/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: node-exporter-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: node-exporter-operator
          control-plane: controller-manager
        name: node-exporter-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: node-exporter-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: node-exporter-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - node-exporter
  - kubernetes
  - prometheus
  links:
  - name: Node Exporter Operator
    url: https://node-exporter-operator.domain
  maturity: alpha
  provider:
    name: node-exporter-provider
  version: 0.0.1
