# permissions for end users to view nodeexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeexporter-viewer-role
rules:
- apiGroups:
  - exporter.slys.dev
  resources:
  - nodeexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exporter.slys.dev
  resources:
  - nodeexporters/status
  verbs:
  - get
