# permissions for end users to edit nodeexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeexporter-editor-role
rules:
- apiGroups:
  - cache.slys.dev
  resources:
  - nodeexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.slys.dev
  resources:
  - nodeexporters/status
  verbs:
  - get
