apiVersion: cache.slys.dev/v1alpha1
kind: NodeExporter
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeexporter-sample
spec:
  nodeExporterSettings:
    enabled: true
  blackboxExporterSettings:
    enabled: false
  kubeStateMetricsSettings:
    enabled: false
