apiVersion: cache.slys.dev/v1alpha1
kind: NodeExporter
metadata:
  name: monitoring-stack
  labels:
    app.kubernetes.io/name: monitoring-stack
    app.kubernetes.io/part-of: node-exporter-operator
spec:
  nodeExporterSettings:
    enabled: true  # Enable Node Exporter for system metrics
  blackboxExporterSettings:
    enabled: true  # Enable Blackbox Exporter for endpoint probing
  kubeStateMetricsSettings:
    enabled: true  # Enable Kube State Metrics for Kubernetes object metrics
